revolist/revogrid

src/components/overlay/readme.md, src/components/revo-grid/revo-grid.scss, src/components/viewport/revogr-viewport.tsx, src/components/viewport/viewport.helpers.ts, src/utilsExternal/generate-data.js
Updated pinned items render.
Now renders only necessary items pinned excepted.
=> Viewport update for pinned items

src/components/data/revogr-data-style.scss, src/components/data/revogr-data.tsx, src/components/header/revogr-header-style.scss, src/components/header/revogr-header.tsx, src/components/overlay/readme.md, src/components/overlay/revogr-edit-style.scss, src/components/overlay/revogr-edit.tsx, src/components/overlay/revogr-order-editor.tsx, src/components/overlay/revogr-order-style.scss, src/components/overlay/revogr-overlay-selection.tsx, src/components/overlay/revogr-overlay-style.scss, src/components/overlay/rowOrderService.ts, src/components/revo-grid/readme.md, src/components/revo-grid/revo-grid.scss, src/components/scrollable/revogr-scroll-style.scss, src/components/scrollable/revogr-scroll-virtual.tsx, src/components/viewport/revogr-viewport-scroll-style.scss, src/components/viewport/revogr-viewport-scroll.tsx, src/components/viewport/revogr-viewport-style.scss, src/components/viewport/revogr-viewport.tsx, src/utilsExternal/generate-data.js
=> Fixed issue with data paste + style restructure

src/components/data/columnService.ts, src/components/data/revogr-data.tsx, src/components/header/readme.md, src/components/order/readme.md, src/components/overlay/readme.md, src/components/revo-grid/readme.md, src/components/revo-grid/revo-grid.tsx, src/interfaces.d.ts, src/services/column.data.provider.ts, src/services/data.provider.ts, src/utilsExternal/generate-data.js
Need extra testing on it.
Now sorting is working per multiple columns, but just for 1 column in time.
=> Updated sorting feature

package.json, src/components.d.ts, src/components/data/columnService.ts, src/components/overlay/cellSelectionService.ts, src/components/overlay/revogr-overlay-selection.tsx, src/interfaces.d.ts, src/store/selection/selection.helpers.ts, src/store/selection/selection.store.ts, src/utils/keyCodes.ts, src/utils/utils.ts
Fixed tab issue
Fixed click on edit issue
Updated focus move on edit
=> Fixed keyboard issues

package.json, src/components.d.ts, src/components/revo-grid/readme.md, src/components/revo-grid/revo-grid.tsx, src/components/viewport/revogr-viewport.tsx, src/index.html, src/services/column.data.provider.ts, src/services/data.provider.ts, src/services/dimension.provider.ts, src/store/storeTypes.ts
Added new methods to control grid scroll position
=> Inriched methods for grid update and scroll

package.json, src/components/data/columnService.ts, src/components/data/revogr-data.tsx, src/components/overlay/cellSelectionService.ts, src/components/revo-grid/revo-grid.tsx, src/index.html, src/store/viewPort/viewport.helpers.ts, src/utilsExternal/generate-data.js
Fixed viewport calculation, fixed range for top row
=> issues fixes

src/components/overlay/editors/text.tsx
#53 Would you accept this pull request to enter data on tab?
Here's a quick gif of how it happens on Excel.
=> Enter data on tab, just like Excel

package.json, src/components/data/columnService.ts, src/interfaces.d.ts
=> row index added

src/components/header/revogr-header-style.scss, src/components/header/revogr-header.tsx, src/components/revo-grid/revo-grid.common-material.scss, src/services/resizable.directive.tsx, src/store/dimension/dimension.helpers.ts, src/store/dimension/dimension.store.ts, src/store/viewPort/viewport.store.ts
Resize update didn't work right because of recombination during change position
=> fixed viewport item recombination for resize

src/store/viewPort/viewport.helpers.ts
If scroll fast range calculation is not right for huge numbers
=> fixed range

package.json, src/components.d.ts, src/components/revo-grid/revo-grid.tsx, src/index.html, src/plugins/export/csv.ts, src/plugins/export/exportFile.ts, src/plugins/export/types.ts, src/services/column.data.provider.ts, src/store/dataSource/data.store.ts
Provided plugin for CVS export
=> Export to csv/excel

package-lock.json, package.json, src/components/overlay/cellSelectionService.ts, src/components/overlay/revogr-edit.tsx, src/components/overlay/revogr-overlay-selection.tsx, src/components/revo-grid/revo-grid.tsx, src/components/viewport/revogr-viewport.tsx, src/index.html, src/plugins/export/csv.ts, src/plugins/export/export.plugin.ts, src/plugins/groupingRow/grouping.const.ts, src/plugins/groupingRow/grouping.row.plugin.ts, src/plugins/groupingRow/grouping.row.renderer.tsx, src/plugins/groupingRow/grouping.service.ts, src/store/selection/selection.store.service.ts
- Added grouping support
- Added proxy for grid render for better filtering and sorting
- Supported export
=> Finished grouping support

readme.md
Add a missing "of" in the readme file.
=> Fix a small typo in readme.md

src/components/clipboard/revogr-clipboard.tsx
Resolves #167 
In the future we can even extract the styles being pasted.
As a recommendation the copy data should also be a generated HTML just how sheets, LibreOffice, etc... generates the data when doing a copy.
=> feat: add HTML to parserPaste

package-lock.json, package.json, src/components.d.ts, src/components/scroll/revogr-viewport-scroll.tsx, src/components/viewport/viewport.helpers.ts, src/index.html, src/utilsExternal/generate-data.js
Provided mousewheel events only in case scrolling present.
Otherwise remove it.
=> #178 bind scrolling event only if scroll present

src/plugins/sorting/sorting.plugin.ts
Fixes https://github.com/revolist/revogrid/issues/140
**Proposed Changes**
Remove sorting from columns on third header click.
**Notes**
Please see the `TODO` in `src/plugins/sorting/sorting.plugin.ts:128` -- I altered this method on the assumption that the `sorting: SortingOrder` object will only have one key-value pair. This change might not work if that assumption isn't true.
=> Unsort columns on third header click

package-lock.json, src/components.d.ts, src/global/_buttons.scss, src/index.html, src/plugins/filter/filter.plugin.tsx, src/plugins/filter/filter.pop.tsx, src/plugins/filter/filter.style.scss
Added a possibility to translate captions, reset filter in one click
=> Improve filter plugin

src/components.d.ts, src/index.html, src/plugins/filter/filter.plugin.tsx, src/plugins/filter/filter.pop.tsx
example `grid.filtering` value inside index.html
```
grid.filter = {
disableDynamicFiltering: true,
localization: {
captions: {
save: 'Apply(save)',
reset: 'Clear(reset)',
cancel: '(cancel)',
}
}
};
```
=> add ability to disable dynamic filtering

src/index.html, src/plugins/filter/filter.plugin.tsx, src/utilsExternal/generate-data.js
=> custom filter

src/components/header/headerRenderer.tsx, src/plugins/sorting/sorting.sign.tsx
In our project, we need to show the sorting icon so that the user understands that it exists. It will be great if you accept our edits, thank you!
=> don't hide sort icon in DOM

src/plugins/filter/filter.button.tsx, src/plugins/filter/filter.plugin.tsx, src/plugins/filter/filter.pop.tsx, src/plugins/filter/readme.md
improve i18n configuration for `revogr-filter-panel`.
=> feat: improve i18n configuration

src/components.d.ts, src/components/data/revogr-data.tsx
Introduced new feature for row render.
=> feature: #446

src/components/overlay/keyboard.service.ts
=> #363 added to v3 support

src/components/revoGrid/revo-grid.tsx
Breaking change:
New event name for range edit.
=> fix: #345 incorrect event name

src/components/revoGrid/revo-grid.tsx
Improved row size runtime, removed lodash from general component.
=> #514 - fixed row size init

src/components/revoGrid/revo-grid.tsx, src/serve/controller.js, src/services/dimension.provider.ts, src/store/vp/viewport.helpers.ts, src/store/vp/viewport.store.ts
- Refactored viewport logic for entities resize
=> fix: #509,refactored viewport logic

package-lock.json, package.json, src/components.d.ts, src/components/revoGrid/revo-grid.tsx, src/plugins/base.plugin.ts
Fix for #517. Improved typing so StencilJs would not ignore types based on class.
=> fix: #517. Improved typing so StencilJs

src/components.d.ts, src/components/revoGrid/revo-grid.tsx, src/plugins/filter/filter.panel.tsx, src/plugins/filter/filter.plugin.tsx, src/types/viewport.interfaces.ts, src/utils/consts.ts
Provided support for shadow dom events
=> feat: #243. Shadow dom support and full stenciljs integration

src/components/header/header-renderer.tsx, src/types/interfaces.ts
feat: Added providesrs to beforeheaderclick & headerdblclick
=> feat: Added providesrs to beforeheaderclick & headerdblclick

src/components.d.ts, src/components/data/cell-renderer.tsx, src/components/data/column.service.ts, src/components/revoGrid/revo-grid.tsx, src/plugins/filter/filter.indexed.ts, src/plugins/filter/filter.panel.tsx, src/plugins/filter/filter.plugin.tsx, src/plugins/filter/filter.types.ts, src/types/interfaces.ts, src/utils/column.utils.ts
Simplified property names
Introduced cellParser function for the future usage with data references
=> Filter refactoring

src/components/data/column.service.ts, src/components/header/header-cell-renderer.tsx, src/components/header/header-renderer.tsx, src/components/header/resizable.directive.tsx, src/components/header/resizable.element.tsx, src/components/header/revogr-header.tsx, src/global/global.ts, src/plugins/wcag/index.ts, src/serve/controller.js, src/themeManager/theme.compact.ts, src/themeManager/theme.default.ts, src/themeManager/theme.material.ts, src/themeManager/theme.service.ts, src/types/interfaces.ts
Column properties are strictly typed and improved for better compatibility with typescript
=> feat: Column properties are strictly typed

src/components.d.ts, src/components/extra/revogr-extra.tsx, src/components/header/revogr-header.tsx, src/components/overlay/autofill.service.tsx, src/components/overlay/revogr-overlay-selection.tsx, src/components/overlay/selection.utils.ts, src/components/revoGrid/revo-grid.tsx, src/components/selectionFocus/revogr-focus.tsx, src/components/selectionTempRange/revogr-temp-range.tsx, src/global/_buttons.scss, src/plugins/filter/filter.panel.tsx, src/plugins/filter/filter.plugin.tsx, src/plugins/filter/filter.style.scss, src/plugins/filter/filter.types.ts, src/store/dimension/dimension.helpers.ts, src/types/interfaces.ts
feat: Improvements on events for filters, temp area selection
feat: Updated filters buttons, removed unused
=> feat: updates on events and filters

src/components/data/column.service.ts, src/plugins/sorting/sorting.plugin.ts, src/utils/column.utils.ts
Added a new feature support for cellParser
This would allow users without changing template and editor change data in one place and see changes applied in all others
=> feat: Cell parser support

src/components.d.ts, src/components/data/cell-renderer.tsx, src/components/data/column.service.ts, src/components/data/revogr-data.tsx, src/serve/data.js, src/types/interfaces.ts
Provided same params for cellTemplate and cellProperties
=> feat: minor improvement to unify properties and cells

readme.md, readme/version.md, src/components.d.ts, src/components/editors/text-editor.ts, src/components/revoGrid/revo-grid.tsx
New method to trigger extra element refresh: `refreshExtraElements`
Avoid increment of internal extra element and allow full rewrite
=> feat: improved extra elements render api

src/components.d.ts, src/components/revoGrid/plugin.service.ts, src/components/revoGrid/revo-grid.tsx
This pull request introduces a new `PluginService` class designed to manage plugins within the Revogrid framework. The `PluginService` handles the lifecycle of plugins, including addition, removal, and retrieval.
- **Plugin Management**: Centralizes the management of plugins through an internal collection.
- **Add User Plugins**: Allows the addition of user-defined plugins, ensuring proper initialization with provided context.
- **Dynamic Removal**: Automatically identifies and removes old plugins that are no longer needed, ensuring efficient resource management.
- **Get Plugins**: Provides methods to retrieve all plugins or specific ones by class type.
- **Destroy Method**: Safely cleans up all plugins, invoking their destroy methods to prevent memory leaks.
- **`internalPlugins`**: An …
=> feat: Implement Plugin Service for Revogrid

src/components/revoGrid/revo-grid.tsx
Store connector be nullable sometime.
This is extra verification.
=> fix: extra verification for selection store connector

src/services/selection.store.connector.ts
Fixed connector store typing build issue
=> fix: typing issue

src/components/overlay/revogr-overlay-selection.tsx, src/components/revoGrid/revo-grid.tsx, src/services/data.provider.ts, src/types/selection.ts
=> #616 - improved setCellData function

src/components/revoGrid/revo-grid.tsx, src/plugins/base.plugin.ts, src/plugins/groupingRow/grouping.const.ts, src/plugins/groupingRow/grouping.row.plugin.ts, src/plugins/groupingRow/grouping.row.renderer.tsx, src/plugins/groupingRow/grouping.row.types.ts, src/plugins/groupingRow/grouping.service.ts, src/serve/controller.js, src/services/dimension.provider.ts, src/types/plugin.types.ts
- New types for plugins addEventListener
- Improved grouping, extended with props and events
- Preserve grouping
=> feat: Preserver grouping, improved plugin types

src/components/revoGrid/styles/revo-grid.common.dark.scss, src/global/_buttons.scss, src/global/_colors.dark.scss, src/plugins/filter/filter.panel.tsx, src/plugins/filter/filter.style.scss, stencil.config.ts
#627 - support dark colors on filter panel
=> #627 - support dark colors on filter panel

src/components/scrollable/revogr-scroll-style.scss
Remove auto-scrollbar on mouse enter which was blocking cells
=> #601 - no scroll bar animation on hover

src/components.d.ts, src/plugins/filter/filter.panel.tsx, src/plugins/filter/filter.plugin.tsx
=> feat: filter hyper

src/components.d.ts, src/components/revoGrid/plugin.service.ts, src/components/revoGrid/revo-grid.tsx, src/index.ts, src/plugins/filter/filter.panel.tsx, src/plugins/filter/filter.plugin.tsx, src/plugins/filter/filter.types.ts, src/types/plugin.types.ts
Fixes on filters, improved hidden rows, new render functions
=> fix: hidden rows in filter plugin

package-lock.json, src/components.d.ts, src/components/revoGrid/revo-grid.tsx, src/plugins/sorting/sorting.func.ts, src/plugins/sorting/sorting.plugin.ts, src/plugins/sorting/sorting.types.ts, src/types/events.ts
Refactor sorting for the future worker support
=> Sorting extracted outside

src/components/revoGrid/revo-grid.tsx, src/components/scroll/revogr-viewport-scroll.tsx, src/plugins/sorting/sorting.plugin.ts, src/serve/data.js, src/services/data.provider.ts, src/services/dimension.provider.ts, src/store/dataSource/data.proxy.ts
- Removed scroll correction, this was deprecated functionality
- Removed viewport update during column/source set on sorting
-`updateViewport` removed extra function with no value from dimension.provider.ts
=> #638 - do not correct scroll

src/components.d.ts, src/components/revoGrid/revo-grid.tsx, src/plugins/groupingRow/grouping.row.plugin.ts, src/plugins/groupingRow/grouping.service.ts, src/plugins/sorting/sorting.func.ts, src/plugins/sorting/sorting.plugin.ts, src/plugins/sorting/sorting.types.ts, src/serve/controller.js, src/types/events.ts
- new sorting api
- grouping works well with sorting now
=> fix: sort issue with grouping

src/components/overlay/autofill.service.tsx, src/components/overlay/revogr-overlay-selection.tsx, src/components/revoGrid/revo-grid.tsx, src/types/selection.ts
=> Provided range area into range fill

src/components/revoGrid/revo-grid.tsx, src/plugins/index.ts
=> New slots added

src/components.d.ts, src/components/revoGrid/revo-grid.tsx, src/plugins/sorting/sorting.plugin.ts, src/types/events.ts
Before source sorting event recovered. Provided comments on sorting events for better accessibility. Initial beforesorting event wasn't covered well with types.
=> breaking change: recovered before source sorting

package-lock.json, package.json, src/components/revoGrid/revo-grid-style.scss, src/plugins/filter/filter.plugin.tsx, src/services/dimension.provider.ts, stencil.config.ts
Upgraded stencil core to the latest version.
Secure grid layout.
=> feat: stencil core up

src/components/data/column.service.ts, src/components/overlay/revogr-overlay-selection.tsx
Updated cell editor function to server outside
=> feat: cell editor func

readme.md, readme/features.md, readme/framework.md, readme/usage.angular.md, readme/usage.js.md, readme/usage.react.md, readme/usage.svelte.md, readme/usage.vue2.md, readme/usage.vue3.md
=> doc: readme fulfilled with refs

src/components/revoGrid/revo-grid.tsx
feat: allow to disable drag and drop plugin
=> feat: allow to disable drag and drop plugin

src/components.d.ts, src/components/data/cell-renderer.tsx, src/components/data/revogr-data.tsx, src/plugins/filter/filter.plugin.tsx, src/plugins/groupingRow/grouping.row.plugin.ts, src/plugins/groupingRow/grouping.row.renderer.tsx, src/plugins/groupingRow/grouping.row.types.ts, src/plugins/groupingRow/grouping.service.ts, src/plugins/index.ts, src/serve/data.js, src/serve/index.html, src/services/data.provider.ts, src/store/dataSource/trimmed.plugin.ts, src/types/interfaces.ts
- Improved grouping functionality
- Minor issues fixes
- Provided extra service exports
=> Grouping exports

src/components.d.ts, src/plugins/filter/filter.panel.tsx, src/plugins/filter/filter.types.ts, src/types/interfaces.ts
=> feat:filter type improved

src/components/revoGrid/revo-grid.tsx, src/components/revoGrid/viewport.service.ts
feat: provided extra type info for selection
=> feat: provided extra type info for selection

src/types/interfaces.ts, src/types/selection.ts
indexes explained for columns and rows
=> indexes explained

src/components/revoGrid/revo-grid.tsx, src/types/interfaces.ts
- Provided typing for additional data
=> Additional data typing
